workflows:
  ios-build:
    name: Healix iOS Build
    working_directory: CodemagicSample
    instance_type: mac_mini_m2
    environment:
      node: latest
      xcode: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Expo prebuild (Generate iOS folder)
        script: npx expo prebuild --platform ios
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build iOS and Generate IPA
        script: |
          cd ios
          WORKSPACE=$(ls | grep \.xcworkspace$ | head -1)
          SCHEME=$(basename "$WORKSPACE" .xcworkspace)
          
          xcodebuild build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination generic/platform=iOS CODE_SIGNING_ALLOWED=NO -derivedDataPath ./build_output
          
          APP_PATH=$(find ./build_output -type d -name "*.app" | head -1)
          
          mkdir Payload
          cp -R "$APP_PATH" Payload/
          zip -r HealixApp.ipa Payload
    artifacts:
      - "**/*.ipa"
